import { cookies } from "next/headers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ThemeToggle";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { LogIn, UserRound } from "lucide-react";
import { DashboardTabs } from "@/components/DashboardTabs";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Supplier Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="grid grid-rows-[5rem_1fr_5rem] h-svh">
            <Header />
            <main className="h-full grid items-center font-[family-name:var(--font-geist-sans)]">
              {children}
            </main>
            <Toaster />
            <footer className="row-start-3 text-muted-foreground flex gap-6 flex-wrap items-center justify-center">
              © {new Date().getFullYear()}
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

async function Header() {
  const user = (await cookies()).get("userId")?.value;
  return (
    <header className="flex p-5 justify-between items-center text-center">
      <Link href="/">
        <span className="font-black tracking-tight">📦 ELMM</span> | Supplier
        Management
      </Link>
      <DashboardTabs user={user} />
      <div className="flex gap-3 items-center">
        <Link href="/login">
          <Avatar>
            <AvatarImage></AvatarImage>
            <AvatarFallback>
              <LogIn />
            </AvatarFallback>
          </Avatar>
        </Link>
        <ModeToggle />
      </div>
    </header>
  );
}
